### ISSUE TITLE
Ще одна локалізація

### ISSUE THREAD

**Issue by darksidecat** [ItzDFPlayer/balatro_ukrainian#1]
Вітаю, побачив вашу локалізацію
Хочу також поділитись локалізацією над якою працюю, поки що вручну перекладено все крім джокерів

Можливо вам буде цікаво
https://github.com/darksidecat/balatro_ukrainian

**Comment by ItzDFPlayer** [comment]
Помітив на наступний день після релізу своєї ваш реліз, як би знав раніше, то допоміг би вам перекласти те, чого ще не зроблено через Pull request
