### ISSUE TITLE
Локалізація спрайтів

### ISSUE THREAD

**Issue by darksidecat** [ItzDFPlayer/balatro_ukrainian#3]
Вітаю, маю питання щодо локалізації спрайтів.

Для локалізації ви використовували цей репозиторій? Якщо так то який шрифт використовували для карт витратників (таро, планет ,спектральних), бо той що використовується тут не підтримує кирилицю.

https://github.com/Signez/balatro-sprites-i18n

**Comment by ItzDFPlayer** [comment]
не знав що цей репозиторій є, весь текст сам витирав та й текст від руки

**Comment by ItzDFPlayer** [comment]
вибачаюсь, забув, за основу брав шрифт Smallest Pixel 7, але редагував його від руки

**Comment by darksidecat** [comment]
Дякую, шрифт дуже допоміг
